name: task_manager
description: "Task Manager App — Electro Pi Assessment"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Functional Error Handling
  fpdart: ^1.1.0

  # HTTP
  dio: ^5.7.0

  # Navigation
  go_router: ^14.6.2

  # Dependency Injection
  get_it: ^8.0.2

  # Secure Storage
  flutter_secure_storage: ^9.2.4

  # Fonts
  google_fonts: ^6.2.1

  # Connectivity (bonus)
  connectivity_plus: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
